# pairing configuration files to their destination
# home refers to the home directory of the current user
paths.home = [".bashrc", ".cargo/config"]

# config refers to the user's config directory ($HOME/.config on linux)
paths.config = ["user-dirs.dirs"]

# the absolute path of any other configuration files which do not reside
# in either the home or default config diretory (ex /etc/gitconfig)
paths.absolute = ["/etc/fish"]
