# specify the packages to install and how to install them
manager.name = 'pacman'
manager.upgrade_args = ['-Syu']
manager.install_args = ['-S', '--noconfirm']
manager.un_install_args = ['-Rncs']
manager.packages = ['firefox',
    'fish',
    'intellij-idea-community-edition',
    'lsd',
    'neofetch',
    'nmap',
    'git']
