# specify the packages to install and how to install them

[manager]
name = 'pacman'
upgrade_args = ['-Syu']
install_args = ['-S', '--noconfirm']
un_install_args = ['-Rncs']
packages = ['firefox',
    'fish',
    'intellij-idea-community-edition',
    'lsd',
    'neofetch',
    'nmap',
    'git']
